spring:
  application:
    name: neko-server

  profiles:
    active: @profile.active@
    group:
      local: other
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。


neko:
  info:
    version: 1.0.0
    base-package: com.neko.boot

